# Generated by Django 3.0.6 on 2020-06-03 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20200603_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 3, 18, 42, 25, 526170)),
        ),
    ]
